baseURL: "https://nh314.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: I'm Phan
permalinks:
  posts: /:title.html
# googleAnalytics: ""

summaryLength: 20

params:
  title: "I'm Phan"
  description: "I specialize in providing services to develop and maintain <br> websites, applications for customers."
  images:
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    facebook: "#"
    twitter: "#"

  contact:
    - "contact@nh314.com"
    - "Skype: phan.nguyen91"

  copyright: "© 2022 I'm Phan - All Rights Reserved"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Contact me"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
